global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 1m

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 15s
    follow_redirects: true
    scheme: http
    static_configs:
      - targets: ['localhost:9090']
  - job_name: node_exporter
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 15s
    follow_redirects: true
    scheme: http
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: cadvisor
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 15s
    follow_redirects: true
    scheme: http
    static_configs:
      - targets:
          - "cadvisor:8080"

