version: '3.8'

services:
  traefik:
    image: traefik:v2.9.6
    ports:
      - "80:80"
      - "8080:8080"
    command:
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedByDefault=false"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure

networks:
  traefik:
    external: true
  
