version: '3'

services:
  loki:
    image: grafana/loki:2.7.1
    container_name: loki
    ports:
      - "3100:3100"
    command:
      #- '--config.file=/etc/loki/config.yaml'
      - '--config.file=/etc/loki/config-extended.yaml'
    volumes:
      #- ./config.yaml:/etc/loki/config.yaml:ro
      - ./config-extended.yaml:/etc/loki/config-extended.yaml:ro
    networks:
      - grafana-loki
    
  grafana:
    image: grafana/grafana:9.3.1
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - grafana-loki

networks:
  grafana-loki:

volumes:
  grafana-data: