version: "3.8"

services:
  node_exporter:
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy: 
        condition: on-failure
    networks:
      - monitoring
    expose:
      - 9100
networks:
  monitoring:
    external: true
